# Generated by Django 4.0.3 on 2022-03-16 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_territory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hero_image', models.CharField(max_length=255)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_sections', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='HeroButton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_text', models.CharField(max_length=255)),
                ('button_link', models.URLField()),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_buttons', to='landing.hero')),
            ],
        ),
    ]
