# Generated by Django 4.0.3 on 2022-03-16 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='territory',
            options={'verbose_name_plural': 'territories'},
        ),
    ]
