# Generated by Django 6.0.6 on 2026-06-25 14:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='long_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
