# Generated by Django 6.0.6 on 2026-06-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_purchaselink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blurb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribution_name', models.CharField()),
                ('short_blurb', models.CharField(blank=True)),
                ('long_blurb', models.CharField(blank=True)),
                ('full_blurb', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
        ),
    ]
