# Generated by Django 6.0.6 on 2026-06-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='blurb',
            name='attribution_book',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='blurb',
            name='attribution_description',
            field=models.CharField(blank=True),
        ),
    ]
