# Generated by Django 6.0.6 on 2026-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_blurb_attribution_book_blurb_attribution_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(blank=True, upload_to='')),
                ('alt_text', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_image',
        ),
    ]
