# Generated by Django 6.0.6 on 2026-06-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcover',
            name='name',
            field=models.CharField(blank=True),
        ),
    ]
