# Generated by Django 6.0.6 on 2026-06-25 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_book_isbn'),
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='seo.seoblock'),
        ),
    ]
