# Generated by Django 6.0.6 on 2026-06-26 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_bookextra'),
        ('images', '0003_alter_image_alt_text_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.image'),
        ),
    ]
