# Generated by Django 6.0.6 on 2026-06-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_cover_image'),
        ('images', '0003_alter_image_alt_text_alter_image_file'),
        ('seo', '0005_remove_seoblock_og_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
        migrations.AlterField(
            model_name='book',
            name='seo_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seo.seoblock'),
        ),
    ]
