# Generated by Django 6.0.6 on 2026-06-26 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_book_cover_image_alter_book_seo_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookCover',
        ),
    ]
