# Generated by Django 6.0.6 on 2026-06-26 12:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_name', models.CharField(blank=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('alt_text', models.CharField(blank=True)),
                ('photo_attribution', models.CharField(blank=True)),
                ('photo_url', models.URLField(blank=True)),
                ('makeup_attribution', models.CharField(blank=True)),
                ('makeup_url', models.URLField(blank=True)),
                ('short_biography', ckeditor.fields.RichTextField(blank=True)),
                ('long_biography', ckeditor.fields.RichTextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField()),
                ('link', models.URLField()),
                ('fa_abbreviation', models.CharField()),
            ],
        ),
    ]
