# Generated by Django 6.0.6 on 2026-06-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
        ('images', '0003_alter_image_alt_text_alter_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='aboutpage',
            name='photo_name',
        ),
    ]
