# Generated by Django 6.0.6 on 2026-06-26 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_aboutpage_photo'),
        ('images', '0003_alter_image_alt_text_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
    ]
