# Generated by Django 6.0.6 on 2026-06-26 11:44

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event_name', models.CharField()),
                ('location_name', models.CharField(blank=True)),
                ('location_address', models.CharField(blank=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PressArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('url', models.URLField(blank=True)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('published_in', models.CharField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecordedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('video', 'video'), ('audio', 'audio')])),
                ('venue', models.CharField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('link', models.URLField(blank=True)),
                ('description', models.CharField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
