# Generated by Django 6.0.6 on 2026-06-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEOBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.CharField(blank=True, max_length=500)),
                ('og_image', models.ImageField(blank=True, upload_to='')),
                ('alt_text', models.TextField(blank=True)),
                ('og_type', models.CharField(choices=[('article', 'article'), ('book', 'book'), ('profile', 'profile'), ('website', 'website')], max_length=20)),
            ],
        ),
    ]
