# Generated by Django 6.0.6 on 2026-06-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoblock',
            name='slug',
            field=models.CharField(blank=True),
        ),
    ]
