# Generated by Django 6.0.6 on 2026-06-26 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_alt_text_alter_image_file'),
        ('seo', '0002_seoblock_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='alt_text',
        ),
    ]
