# Generated by Django 6.0.6 on 2026-06-26 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_remove_seoblock_og_image_seoblock_og_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='og_image_file',
        ),
    ]
