# Generated by Django 6.0.6 on 2026-06-26 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_alt_text_alter_image_file'),
        ('seo', '0005_remove_seoblock_og_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoblock',
            name='og_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image'),
        ),
    ]
