# Generated by Django 6.0.6 on 2026-06-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Short',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(choices=[('short_fiction', 'short fiction'), ('poetry', 'poetry'), ('essay', 'essay')])),
                ('title', models.CharField()),
                ('piece_url', models.URLField(blank=True)),
                ('published_in', models.CharField(blank=True)),
                ('issue', models.CharField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('audio_available_url', models.URLField(blank=True)),
                ('word_count', models.IntegerField(blank=True)),
                ('genre', models.CharField(blank=True, choices=[('fantasy', 'Fantasy'), ('science_fiction', 'Science Fiction'), ('horror', 'Horror')])),
            ],
        ),
    ]
