# Generated by Django 6.0.6 on 2026-06-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_reprintrecord_reviewrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='word_count',
            field=models.CharField(blank=True),
        ),
    ]
