# Generated by Django 6.0.6 on 2026-06-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_alter_short_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reprintrecord',
            name='piece',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shorts.short'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reprintrecord',
            name='venue_url',
            field=models.URLField(blank=True),
        ),
    ]
